version: "3"

services:
    php:
        build:
            context: "./php"
            dockerfile: Dockerfile
            args:
                - APP_USER_UID=${APP_USER_UID}
                - APP_GROUP_GID=${APP_GROUP_GID}
                - APP_USER=www-data
                - APP_GROUP=www-data
        working_dir: /var/www/app
        volumes:
            - app-volume:/var/www/app
            - php-logs:/var/log/php
        links:
            - db
        restart: "no"
        tty: true
        networks:
            - app-network
    webserver:
        build:
            context: "./nginx"
            dockerfile: Dockerfile
            args:
                - APP_USER_UID=${APP_USER_UID}
                - APP_GROUP_GID=${APP_GROUP_GID}
                - APP_USER=www-data
                - APP_GROUP=www-data
        volumes:
            - app-volume:/var/www/app
            - webserver-logs:/var/log/webserver
        links:
            - php
        ports:
            - '${INTERFACE}:80:80'
        networks:
            - app-network
        restart: "no"
        tty: true
    db:
        image: postgres:16.1
# https://stackoverflow.com/questions/41637505/how-to-persist-data-in-a-dockerized-postgres-database-using-volumes
# https://stackoverflow.com/questions/48862633/how-to-setup-volume-for-postgres-log-folder-permission-denied-error
        volumes:
            - db:/var/lib/postgresql/data
            - db-logs:/logs
        ports:
            - '${INTERFACE}:5432:5432'
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_DB: ${DB_NAME}
        restart: "no"
        tty: true
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: ${SUBNET}

volumes:
    app-volume:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ./${SITE_DIR}
    php-logs:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ./logs/php
    webserver-logs:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ./logs/webserver
    db-logs:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ./logs/postgres
    db:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ./db
