# https://proglib.io/p/kak-zapustit-nginx-v-docker-2020-05-12
user www-data www-data;
worker_processes auto;

events { worker_connections 1024; }

http {
    include /etc/nginx/conf.d/*.conf;
    include /etc/nginx/sites-available/*;

    gzip off;
    gunzip off;
}