# https://proglib.io/p/kak-zapustit-nginx-v-docker-2020-05-12
user www-data www-data;
worker_processes auto;

events { worker_connections 1024; }

http {
    server {
        server_tokens off;

        listen 80;
        root /var/www/app;
        include /etc/nginx/mime.types;

        location / {
            try_files $uri $uri/ $uri/index.php $uri/index.html;
        }

        gzip off;
        gunzip off;
    }
}