[php]
date.timezone = "Atlantic/Azores"
display_errors = Off
error_log = "/var/log/php/error.log"
#error_reporting = E_ALL ^ E_DEPRECATED
#log_errors = Off
#display_startup_errors = Off

#max_input_time=6000
#max_execution_time=6000

#[xdebug]
#xdebug.mode=debug
#xdebug.start_with_request=trigger
#xdebug.discover_client_host=true
#xdebug.client_host=host.docker.internal